// @flow
export const charAt = (bb: number) => (aa: string) => aa.charAt(bb);
export const charCodeAt = (bb: number) => (aa: string) => aa.charCodeAt(bb);
export const codePointAt = (bb: number) => (aa: string) => aa.codePointAt(bb);
export const concat = (bb: string) => (aa: string) => aa.concat(bb);
export const endsWith = (bb: string) => (aa: string) => aa.endsWith(bb);
export const fixed = (bb: number) => (aa: string) => aa.fixed(bb);
export const includes = (bb: string) => (aa: string) => aa.includes(bb);
export const indexOf = (bb: string) => (aa: string) => aa.indexOf(bb);
export const lastIndexOf = (bb: string) => (aa: string) => aa.lastIndexOf(bb);
export const localeCompare = (bb: string) => (aa: string) => aa.localeCompare(bb);
export const match = (bb: string) => (aa: string) => aa.match(bb);
export const normalize = (bb: string) => (aa: string) => aa.normalize(bb);
export const padEnd = (length: number, padString?: string) => (aa: string) => aa.padEnd(length, padString);
export const padStart = (length: number, padString?: string) => (aa: string) => aa.padStart(length, padString);
export const repeat = (bb: number) => (aa: string) => aa.repeat(bb);
export const replace = (match: string|RegExp, replace?: string|Function) => (aa: string) => aa.replace(match, replace);
export const search = (bb: string) => (aa: string) => aa.search(bb);
export const slice = (bb: string) => (aa: string) => aa.slice(bb);
export const small = (bb: string) => (aa: string) => aa.small(bb);
export const split = (bb: string) => (aa: string) => aa.split(bb);
export const strike = (bb: string) => (aa: string) => aa.strike(bb);
export const sub = (bb: string) => (aa: string) => aa.sub(bb);
export const substr = (bb: string) => (aa: string) => aa.substr(bb);
export const substring = (bb: string) => (aa: string) => aa.substring(bb);
export const sup = (bb: string) => (aa: string) => aa.sup(bb);
export const startsWith = (bb: string) => (aa: string) => aa.startsWith(bb);
export const toString = (bb: string) => (aa: string) => aa.toString(bb);
export const trim = (bb: string) => (aa: string) => aa.trim(bb);
export const trimLeft = (bb: string) => (aa: string) => aa.trimLeft(bb);
export const trimRight = (bb: string) => (aa: string) => aa.trimRight(bb);
export const toLocaleLowerCase = (bb: string) => (aa: string) => aa.toLocaleLowerCase(bb);
export const toLocaleUpperCase = (bb: string) => (aa: string) => aa.toLocaleUpperCase(bb);
export const toLowerCase = (bb: string) => (aa: string) => aa.toLowerCase(bb);
export const toUpperCase = (bb: string) => (aa: string) => aa.toUpperCase(bb);
export const valueOf = (bb: string) => (aa: string) => aa.valueOf(bb);
export const trimStart = (bb: string) => (aa: string) => aa.trimStart(bb);
export const trimEnd = (bb: string) => (aa: string) => aa.trimEnd(bb);
